### ISSUE TITLE
Fail to load content of a submodule

### ISSUE THREAD

**Issue by kkris** [jonashaag/klaus#1]
I get this Traceback, when entering a submodule (i tried with the cream/cream repo):

``` python
Traceback (most recent call last):
  File "nano/nano.py", line 179, in __call__
    retval = callback(environ, **kwargs)
  File "/tmp/git/klaus/klaus.py", line 31, in wrapper
    **callback(env, **kwargs))
  File "/tmp/git/klaus/klaus.py", line 159, in __init__
    super(BaseRepoView, self).__init__(env)
  File "/tmp/git/klaus/klaus.py", line 122, in __init__
    self.view()
  File "/tmp/git/klaus/klaus.py", line 184, in view
    self['tree'] = self.listdir(self['path'])
  File "/tmp/git/klaus/klaus.py", line 199, in listdir
    for name, entry in self['repo'].listdir(self['commit'], path):
  File "/tmp/git/klaus/repo.py", line 89, in listdir
    tree = self.get_tree(commit, root)
  File "/tmp/git/klaus/repo.py", line 85, in get_tree
    tree = self[tree[directory][1]]
  File "/usr/lib/python2.7/site-packages/dulwich/repo.py", line 996, in __getitem__
    return self.object_store[self.refs[name]]
  File "/usr/lib/python2.7/site-packages/dulwich/repo.py", line 270, in __getitem__
    raise KeyError(name)
KeyError: '38bdce3108e1002cf4d99e44a8242f97ccd66e6c'

```

**Comment by jonashaag** [comment]
There's a `parse_submodules` function now

**Comment by jelmer** [comment]
This doesn't require any further changes in Dulwich; the web UI needs to switch repository locations when it encounters a submodule. 

Initial work on this can be found here:

https://github.com/jelmer/klaus/tree/submodules

This adds the right links, but it needs further work:

 * some CSS to distinguish submodules from directories
 * support for slashes in repository names (as you can see when you click on one of the submodule paths). I'm not sure how to do this with flask

**Comment by jelmer** [comment]
(or https://jelmer.uk/code/klaus/tree/submodules/)

**Comment by jonashaag** [comment]
Cool! LGTM so far.

The problem with slashes isn't only Flask routing; it guess that shouldn't be too complicated. It's also that we don't necessarily have submodules in the internal `Klaus.repos` dictionary, which is a basename -> Repo object map. So if we were to use `/toprepo/submodule/README.md` style URLs and could figure out that this is actually accessing a file from `submodule`, we still wouldn't know how to resolve `toprepo/submodule` in the repository list.

One solution would be to automatically add any submodules to the repository dictionary with their `toprepo/submodule` key, but don't show them on the repository list page. This requires to recursively look for submodules on initialisation for Smart HTTP support (unless we don't want to support Smart HTTP for submodules).

Another idea is to look for a top-level repository named `submodule` and assume that it must be the same as `toprepo/submodule`. As a sanity check, we could check if the submodule commit ID exists there. However this makes viewing different submodules with the same name impossible, unless we use a full dictionary scan for the commit ID, ignoring the repository name.

A third approach could work as follows: When initialising the repository dictionary, for each repository check if it's a submodule of another repository (this could be tricky) and add it to the repos dictionary both as `submodule` and `toprepo/submodule`. Then we could simply use the `toprepo/submodule` key into the dictionary list and could be sure we're getting the correct repository. We'd actually have to do this recursively for any combination of `top/sub` prefixes.

Not sure what's the best approach. Do you have other ideas?

**Comment by jelmer** [comment]
Getting back to this after giving it some thought...

On Thu, Jan 26, 2017 at 12:51:42PM -0800, Jonas Haag wrote:
> The problem with slashes isn't only Flask routing; it guess that shouldn't be too complicated. It's also that we don't necessarily have submodules in the internal `Klaus.repos` dictionary, which is a basename -> Repo object map. So if we were to use `/toprepo/submodule/README.md` style URLs and could figure out that this is actually accessing a file from `submodule`, we still wouldn't know how to resolve `toprepo/submodule` in the repository list.
Ah, I see.

This style doesn't work if the submodule points at a different
repository at different points in time. We'd need to have something in
the URL to account for that.

> One solution would be to automatically add any submodules to the repository dictionary with their `toprepo/submodule` key, but don't show them on the repository list page. This requires to recursively look for submodules on initialisation for Smart HTTP support (unless we don't want to support Smart HTTP for submodules).
I think starting off without exposing submodules in the smart
server would be fine, so long as the user can browse the contents of
the submodule.

What the user checks out if they run 'git submodule init / git
submodule update' will be the URL set in .gitmodules. That's almost
certainly not going to be a URL under <baserepo>.

> Another idea is to look for a top-level repository named `submodule` and assume that it must be the same as `toprepo/submodule`. As a sanity check, we could check if the submodule commit ID exists there. However this makes viewing different submodules with the same name impossible, unless we use a full dictionary scan for the commit ID, ignoring the repository name.
> 
> A third approach could work as follows: When initialising the repository dictionary, for each repository check if it's a submodule of another repository (this could be tricky) and add it to the repos dictionary both as `submodule` and `toprepo/submodule`. Then we could simply use the `toprepo/submodule` key into the dictionary list and could be sure we're getting the correct repository. We'd actually have to do this recursively for any combination of `top/sub` prefixes.
> 
> Not sure what's the best approach. Do you have other ideas?

As a first step, perhaps we can start off by adding a page explaining
that something is a submodule, rather than throwing an error. We could
do this by having a page like:

/REPO/submodule/BRANCH/SUBMODULE-PATH

... that we can link to for submodules (akin to
/REPO/tree/BRANCH/TREE-PATH).

Initially this could just say "There is a submodule here. You can
clone the repository at git://blah/blah to get it"

In the future, we could add something more complicated on this page or
have it redirect to the real repository using one of the suggestions
you mention above.

Jelmer
