### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by sbraz** [jonashaag/klaus#159]
Hi, it seems that the Web UI works well with Python 3 and dulwich 0.13.0. However, Smart HTTP does not:
```
127.0.0.1 - - [26/Apr/2016 14:41:48] "GET /klaus/info/refs?service=git-upload-pack HTTP/1.1" 403 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/lib64/python3.5/site-packages/werkzeug/serving.py", line 184, in execute
    write(data)
  File "/usr/lib64/python3.5/site-packages/werkzeug/serving.py", line 164, in write
    assert isinstance(data, bytes), 'applications must write bytes'
AssertionError: applications must write bytes
```
I don't know if this is an issue with dulwich or klaus but I thought it would be nice to have an open bug to track the state of Python 3 compatibility.

**Comment by jonashaag** [comment]
Works for me, are you sure you're using Dulwich 0.13.0?

**Comment by sbraz** [comment]
My bad, I was using dulwich 0.12.0. I'll add Python 3 compatibility to the Gentoo package, thanks :)

**Comment by sbraz** [comment]
Does the ctags lib work with Python 3 though? With all those `PyNumber_Int`s https://github.com/hddmet/python-ctags/blob/master/src/_readtags.c#L21

**Comment by jonashaag** [comment]
It doesn't

**Comment by sbraz** [comment]
That's too bad :/ There probably isn't much to do since the code already supports old Python 3 versions. I'm just curious about what those functions do:
https://github.com/hddmet/python-ctags/blob/master/src/_readtags.c#L2699

**Comment by sbraz** [comment]
Hi, I ported your ctags code to Python 3: feel free to reuse it or pull it directly:
https://github.com/sbraz/klaus/commit/aca3489d7ea231601ebf241b4726cd16a647df3a
python-ctags works fine with Python 3, you just need to run `cython _readtags.pyx` to re-generate the `_readtags.c` file and it will build.

**Comment by jonashaag** [comment]
Cool!

> python-ctags works fine with Python 3, you just need to run cython _readtags.pyx to re-generate the _readtags.c file and it will build. Oh, and fix the relative import:

Could we get this change released on PyPI first? Maybe open a PR on python-ctag's repo, though I doubt it's still being actively maintained. Maybe you/I have to fork?

**Comment by sbraz** [comment]
Yeah the author hasn't been around much lately. I'll make a PR first, just in case. I don't really know the code in-depth so I'd like to avoid having to maintain a fork :)

**Comment by sbraz** [comment]
@jonashaag PR opened.

**Comment by jonashaag** [comment]
Thanks a lot! Let's wait for a few days, and if nothing happens, I'll host the fork myself.

**Comment by 95A31** [comment]
Hi,
I have the following error about tags:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.5/site-packages/klaus/utils.py", line 58, in __call__
    return super(ProxyFix, self).__call__(environ, start_response)
  File "/usr/lib/python3.5/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/klaus/views.py", line 79, in dispatch_request
    self.make_template_context(repo, rev, path.strip('/'))
  File "/usr/lib/python3.5/site-packages/klaus/views.py", line 144, in make_template_context
    super(HistoryView, self).make_template_context(*args)
  File "/usr/lib/python3.5/site-packages/klaus/views.py", line 120, in make_template_context
    super(TreeViewMixin, self).make_template_context(*args)
  File "/usr/lib/python3.5/site-packages/klaus/views.py", line 98, in make_template_context
    'tags': repo.get_tag_names(),
  File "/usr/lib/python3.5/site-packages/klaus/repo.py", line 95, in get_tag_names
    return self.get_ref_names_ordered_by_last_commit('refs/tags')
  File "/usr/lib/python3.5/site-packages/klaus/repo.py", line 84, in get_ref_names_ordered_by_last_commit
    sorted_names = sorted(refs.keys(), key=get_commit_time, reverse=True)
  File "/usr/lib/python3.5/site-packages/klaus/repo.py", line 78, in get_commit_time
    return obj.tag_time
  File "/usr/lib/python3.5/site-packages/dulwich/objects.py", line 149, in get
    return getattr(obj, "_"+name)

**Comment by sbraz** [comment]
@95A31 How do you trigger the error? Maybe it would be easier to follow if you opened a new issue.

**Comment by 95A31** [comment]
@sbraz My bad, this error do not involve ctags.
