### ISSUE TITLE
AttributeError: _tag_time

### ISSUE THREAD

**Issue by 95A31** [jonashaag/klaus#164]
Hi,
I have this issue when I click on the git directory:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/klaus/views.py", line 79, in dispatch_request
    self.make_template_context(repo, rev, path.strip('/'))
  File "/usr/lib/python3.5/site-packages/klaus/views.py", line 144, in make_template_context
    super(HistoryView, self).make_template_context(*args)
  File "/usr/lib/python3.5/site-packages/klaus/views.py", line 120, in make_template_context
    super(TreeViewMixin, self).make_template_context(*args)
  File "/usr/lib/python3.5/site-packages/klaus/views.py", line 98, in make_template_context
    'tags': repo.get_tag_names(),
  File "/usr/lib/python3.5/site-packages/klaus/repo.py", line 95, in get_tag_names
    return self.get_ref_names_ordered_by_last_commit('refs/tags')
  File "/usr/lib/python3.5/site-packages/klaus/repo.py", line 84, in get_ref_names_ordered_by_last_commit
    sorted_names = sorted(refs.keys(), key=get_commit_time, reverse=True)
  File "/usr/lib/python3.5/site-packages/klaus/repo.py", line 78, in get_commit_time
    return obj.tag_time
  File "/usr/lib/python3.5/site-packages/dulwich/objects.py", line 149, in get
    return getattr(obj, "_"+name)
AttributeError: _tag_time
```

**Comment by jonashaag** [comment]
Could you try this with Python 2? Which version of Dulwich are you using?

**Comment by 95A31** [comment]
I am using Dulwich 0.13. How I can force Python2?

**Comment by jonashaag** [comment]
You install klaus in a Python 2 virtualenv, or, if you don't use virtualenv, you use `pip2`.

**Comment by 95A31** [comment]
Done by pip2:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/klaus/views.py", line 79, in dispatch_request
    self.make_template_context(repo, rev, path.strip('/'))
  File "/usr/lib/python2.7/site-packages/klaus/views.py", line 144, in make_template_context
    super(HistoryView, self).make_template_context(*args)
  File "/usr/lib/python2.7/site-packages/klaus/views.py", line 120, in make_template_context
    super(TreeViewMixin, self).make_template_context(*args)
  File "/usr/lib/python2.7/site-packages/klaus/views.py", line 98, in make_template_context
    'tags': repo.get_tag_names(),
  File "/usr/lib/python2.7/site-packages/klaus/repo.py", line 95, in get_tag_names
    return self.get_ref_names_ordered_by_last_commit('refs/tags')
  File "/usr/lib/python2.7/site-packages/klaus/repo.py", line 84, in get_ref_names_ordered_by_last_commit
    sorted_names = sorted(refs.keys(), key=get_commit_time, reverse=True)
  File "/usr/lib/python2.7/site-packages/klaus/repo.py", line 78, in get_commit_time
    return obj.tag_time
  File "/usr/lib/python2.7/site-packages/dulwich/objects.py", line 149, in get
    return getattr(obj, "_"+name)
AttributeError: _tag_time
```

**Comment by 95A31** [comment]
@jonashaag I have removed all unecessary git tags and now it is working, probably my git status was bad.

**Comment by jonashaag** [comment]
If you could send me a copy of the repository that produced the error that would be cool (I promise not to do bad stuff with it like distribute etc.)

**Comment by 95A31** [comment]
Sure: https://github.com/95A31/android_kernel_msm.git

**Comment by jonashaag** [comment]
Seems like we don't use the proper API there, see jelmer/dulwich#430

**Comment by simias** [comment]
I've just stumbled upon the same issue using klaus-1.0.1 installed from pip and running on python 2.7:

The repository is a fork of the linux kernel source tree:

```
127.0.0.1 - - [20/Jan/2017 12:17:48] "GET /linux/ HTTP/1.1" 500 -
127.0.0.1 - - [20/Jan/2017 12:17:48] "GET /favicon.ico HTTP/1.1" 301 -
127.0.0.1 - - [20/Jan/2017 12:17:48] "GET /favicon.ico/ HTTP/1.1" 404 -
127.0.0.1 - - [20/Jan/2017 12:17:48] "GET /favicon.ico/ HTTP/1.1" 404 -
[2017-01-20 12:18:28,731] ERROR in app: Exception on /linux/ [GET]
Traceback (most recent call last):
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/klaus/views.py", line 79, in dispatch_request
    self.make_template_context(repo, rev, path.strip('/'))
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/klaus/views.py", line 144, in make_template_context
    super(HistoryView, self).make_template_context(*args)
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/klaus/views.py", line 120, in make_template_context
    super(TreeViewMixin, self).make_template_context(*args)
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/klaus/views.py", line 98, in make_template_context
    'tags': repo.get_tag_names(),
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/klaus/repo.py", line 95, in get_tag_names
    return self.get_ref_names_ordered_by_last_commit('refs/tags')
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/klaus/repo.py", line 84, in get_ref_names_ordered_by_last_commit
    sorted_names = sorted(refs.keys(), key=get_commit_time, reverse=True)
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/klaus/repo.py", line 78, in get_commit_time
    return obj.tag_time
  File "/home/git/klaus/klaus-sandbox/lib/python2.7/site-packages/dulwich/objects.py", line 149, in get
    return getattr(obj, "_"+name)
AttributeError: _tag_time
```

Judging by the backtrace the error could be in the dulwich library itself?

I'm not exactly a pro in python but do let me know if I can do anything to help debug that.

**Comment by simias** [comment]
Some more digging:

The object that causes the crash is

```
<Tag 733ad933f62e82ebc92fed988c7f0795e64dea62>
```

Which indeed doesn't have a date (or author) unlike more recent tags:

```
$ git show 733ad933f62e82ebc92fed988c7f0795e64dea62
tag v2.6.13-rc1

Linux v2.6.13-rc1
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.2.4 (GNU/Linux)

iD8DBQBCwjh2F3YsRnbiHLsRAsZoAJ0SPjlMv9YJ0t8CK1aXxY7FEhxx3gCeLQdI
lMoytHCu5FBWnUASNNYFonc=
=KfmA
-----END PGP SIGNATURE-----

commit 4c91aedb75d1b87deccf16d58f67fb46402d7d44
Author: Linus Torvalds <torvalds@ppc970.osdl.org>
Date:   Tue Jun 28 22:57:29 2005 -0700

    Linux v2.6.13-rc1
    
    Ok, a lot of things were pending after the 2.6.12 release, let's try to
    start calming things down again.

diff --git a/Makefile b/Makefile
index 1fdace757e15..77aab7bdde01 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 VERSION = 2
 PATCHLEVEL = 6
-SUBLEVEL = 12
-EXTRAVERSION =
+SUBLEVEL = 13
+EXTRAVERSION =-rc1
 NAME=Woozy Numbat
 
 # *DOCUMENTATION*
```

However by adding some debugging in dulwich I found out that the problem was that the `_tag_time` was never set because this tag doesn't contain any `_TAGGER_HEADER`.

Doing some googling lead me to this: https://www.spinics.net/lists/git/msg121695.html

So apparently old versions of git didn't set this header.

I feel like dulwich should handle this more nicely (by returning `None` in this situation?) but I don't think there's any way to retrieve an actual date from these old tags, besides using the date of the tagged commit itself I suppose.

**Comment by jonashaag** [comment]
@simias Thanks a lot for debugging and fixing this in Dulwich! Can we consider this issue solved?

**Comment by simias** [comment]
I think so, yeah. I haven't thoroughly tested klaus with the patched dulwich but as far as I can tell it handles the time-less tags gracefully.
