### ISSUE TITLE
Error on blame function

### ISSUE THREAD

**Issue by 95A31** [jonashaag/klaus#165]
Hi,
when I click on blame I have this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/klaus/views.py", line 80, in dispatch_request
    return self.get_response()
  File "/usr/lib/python3.5/site-packages/klaus/views.py", line 83, in get_response
    return render_template(self.template_name, **self.context)
  File "/usr/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/klaus/templates/blame_blob.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/usr/lib/python3.5/site-packages/klaus/templates/base.html", line 1, in top-level template code
    {% extends 'skeleton.html' %}
  File "/usr/lib/python3.5/site-packages/klaus/templates/skeleton.html", line 2, in top-level template code
    <title>{% block title %}{% endblock %} - {{ SITE_NAME }}</title>
  File "/usr/lib/python3.5/site-packages/klaus/templates/blame_blob.html", line 4, in block "title"
    {{ path }} - {{ super() }}
  File "/usr/lib/python3.5/site-packages/klaus/templates/base.html", line 4, in block "title"
    {{ repo.name }} ({{ rev|shorten_sha1 }})
  File "/usr/lib/python3.5/site-packages/klaus/utils.py", line 171, in shorten_sha1
    if re.match(r'[a-z\d]{20,40}', str(sha1)):
  File "/usr/lib/python3.5/re.py", line 163, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a bytes pattern on a string-like object
```

I fixed replacing sha1 with str(sha1) in shorten_sha1 function.

**Comment by jonashaag** [comment]
Thanks for the report. Pull requests welcome. (Please include a unit test.)

**Comment by jonashaag** [comment]
Haha, the blame tests currently don't even test any "good" scenarios, only "bad" ones. This is probably also why the test suite doesn't break on Python 3.

**Comment by sbraz** [comment]
@jonashaag I can work on this, what do you think of doing
```py
if isinstance(sha1, bytes):
    sha1 = sha1.decode('ascii', errors='ignore')
```
instead of using `str()`? Or maybe I should decode using 'utf-8', I'm not sure…

**Comment by jonashaag** [comment]
You can simply use `sha.decode('ascii')`.

**Comment by jonashaag** [comment]
Why does it say "cannot use a bytes pattern on a string-like object" whiile the pattern is a string?

**Comment by sbraz** [comment]
The pattern is not always a string, sometimes it's a bytes object, so we can't decode unconditionally (or did you mean that I could just skip the errors part?).

**Comment by jonashaag** [comment]
Then the error message doesn't make sense, it's complaining that we're looking for a byte pattern on a string object, but the pattern is obviously string.

**Comment by sbraz** [comment]
The error is `TypeError: cannot use a string pattern on a bytes-like object`, I assume he modified the regex to a bytes object thinking it would fix the problem.

**Comment by jonashaag** [comment]
OK, then I'd prefer to do the decoding in the places where `shorten_sha` is called into. If it's the templates, I wonder if we should convert the `rev` variable to string when constructing the context -- I don't see any reason to have a bytes object in the templates, but maybe it breaks things.

**Comment by sbraz** [comment]
I'll leave it to you then, I don't know the whole code :)

**Comment by jonashaag** [comment]
If you want you can write a test for blame in the meantime :) I think we should simply make sure `rev` is a string here https://github.com/jonashaag/klaus/blob/c816a41537c81eea2a30d72df07bc7cca0caeb09/klaus/views.py#L44
