### ISSUE TITLE
ValueError: Attempted relative import in non-package in uwsgi. 

### ISSUE THREAD

**Issue by Atroskelis** [jonashaag/klaus#180]
Running " uwsgi --plugin python,http --http :9090 --wsgi-file wsgi.py" results in 

```
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "wsgi.py", line 2, in <module>
    from .app_args import get_args_from_env
ValueError: Attempted relative import in non-package
```

nor running as python -m : 

``` python -m wsgi
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/klaus/wsgi.py", line 2, in <module>
    from .app_args import get_args_from_env
ValueError: Attempted relative import in non-package```

**Comment by jonashaag** [comment]
You gotta run it with `klaus.contrib.wsgi` as module, not the `wsgi.py` directly

**Comment by jonashaag** [comment]
See https://github.com/jonashaag/klaus#using-a-real-server
