### ISSUE TITLE
WSGI script for mod_wsgi ignores bare repos.

### ISSUE THREAD

**Issue by Atroskelis** [jonashaag/klaus#181]
The script at [the wiki](https://github.com/jonashaag/klaus/wiki/Apache---mod_wsgi-deployment) that should be called by httpd/apache does not seem to work with bare repos.

Repos are valid, cause they work with "uwsgi" command just fine.

httpd error_log output:

```
mod_wsgi (pid=23316): Target WSGI script '/usr/lib/python2.7/site-packages/klaus/wsgiscript.py' cannot be loaded as Python module.
mod_wsgi (pid=23316): Exception occurred processing WSGI script '/usr/lib/python2.7/site-packages/klaus/wsgiscript.py'.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/klaus/wsgiscript.py", line 23, in <module>
    application = make_app(REPOSITORIES, TITLE)
  File "/usr/lib/python2.7/site-packages/klaus/__init__.py", line 121, in make_app
    ctags_policy,
  File "/usr/lib/python2.7/site-packages/klaus/__init__.py", line 20, in __init__
    repo_objs = [FancyRepo(path) for path in repo_paths]
  File "/usr/lib64/python2.7/site-packages/dulwich/repo.py", line 694, in __init__
    "No git repository was found at %(path)s" % dict(path=root)
NotGitRepository: No git repository was found at /home/oxidized/remote-config-git/configs.git

```
Perhaps related to #176 ?

**Comment by jonashaag** [comment]
Does it work if you use the command line program? Are you sure `config.git` is a repo? Klaus is actually well-tested against bare and non-bare repos

**Comment by Atroskelis** [comment]
I assume you mean the uwsgi ?

This one does not complain about the repo, and will complain if i mistype it. 

```
root@oxidized-core ~]# uwsgi --plugin python,http --http :9090 --wsgi klaus.contrib.wsgi --env KLAUS_SITE_NAME="Klaus Demo"  --env KLAUS_REPOS="/home/oxidized/remote-config-git/configs.git"
*** Starting uWSGI 2.0.14 (64bit) on [Mon Mar 27 23:46:48 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 13 January 2017 23:06:53
os: Linux-3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016
nodename: oxidized-core
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root
detected binary path: /usr/sbin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 15097
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on <ip>:9090 fd 4
spawned uWSGI http 1 (pid: 22485)
uwsgi socket 0 bound to TCP address 127.0.0.1:41421 (port auto-assigned) fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x14bd940
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x14bd940 pid: 22484 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 22484, cores: 1)
```

**Comment by jonashaag** [comment]
Could you post a `print(repo_paths)` in `__init__`?

**Comment by Atroskelis** [comment]
I added the line at row 27 in `/usr/lib/python2.7/site-packages/klaus/__init__.py`

And ran the above command:

```
[root@oxidized-core dulwich]# uwsgi --plugin python,http --http :9090 --wsgi klaus.contrib.wsgi --env KLAUS_SITE_NAME="Klaus Demo"  --env KLAUS_REPOS="/home/oxidized/remote-config-git/configs.git"
*** Starting uWSGI 2.0.14 (64bit) on [Tue Mar 28 10:54:56 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 13 January 2017 23:06:53
os: Linux-3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016
nodename: oxidized-core
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /usr/lib64/python2.7/site-packages/dulwich
detected binary path: /usr/sbin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 15097
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 91.212.162.27:9090 fd 4
spawned uWSGI http 1 (pid: 22517)
uwsgi socket 0 bound to TCP address 127.0.0.1:39503 (port auto-assigned) fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x206e920
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
['/home/oxidized/remote-config-git/configs.git']
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x206e920 pid: 22516 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 22516, cores: 1)
```
And it displays the path in the output.

Here's the modified sample wsgi script  as well : 
```
# -*- coding: UTF-8 -*-
# wsgi.py

# Optional: if you install klaus in a virtualenv, you need to tell Python 
# about your environment's site-packages directory
import site
site.addsitedir('/usr/lib/python2.7/site-packages')


# Your klaus site title. Make sure it's a unicode object if it 
# contains non-ascii characters
TITLE = u"Config backups"

# A list of paths pointing to your git repositories
REPOSITORIES = ["/home/oxidized/remote-config-git/configs.git"]

# klaus provides a make_app function that creates a WSGI application
from klaus import make_app

# Create the application
application = make_app(REPOSITORIES, TITLE)
```

**Comment by jonashaag** [comment]
Hm, this doesn't make sense to me. What happens if you do

```
python -c 'import dulwich.repo; dulwich.repo.Repo("/home/oxidized/remote-config-git/configs.git")'
```

**Comment by Atroskelis** [comment]
Uhm, no output :(

```
[root@oxidized-core klaus]# python -c 'import dulwich.repo; dulwich.repo.Repo("/home/oxidized/remote-config-git/configs.git")'
[root@oxidized-core klaus]# 
```

**Comment by jonashaag** [comment]
That's actually good. So it's not a problem of Dulwich not recognising your repo.

Then I guess it must have something to do with permissions, our some other environment differences on your server.

**Comment by Atroskelis** [comment]
I've managed to fix the problem.

It indeed was a permissions issue. I set the VirtualHost to run as apache user, but apache user did not have rights to access the git repo, but it did had rights to access the script. 

Many many thanks!
