### ISSUE TITLE
Python3: 500 Internal Server Error using blame functionality

### ISSUE THREAD

**Issue by FriedrichFroebel** [jonashaag/klaus#194]
When trying to use `klaus` with `python3.4`, I get the following error inside my `gunicorn` log when trying to open `blame` for a file:

```
ERROR in app: Exception on /klaus/blame/master/README.rst [GET]
Traceback (most recent call last):
   File "/home/me/.local/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
     response = self.full_dispatch_request()
   File "/home/me/.local/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/home/me/.local/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/home/me/.local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
     raise value
   File "/home/me/.local/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
     rv = self.dispatch_request()
   File "/home/me/.local/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/home/me/.local/lib/python3.4/site-packages/flask/views.py", line 84, in view
     return self.dispatch_request(*args, **kwargs)
   File "/home/me/.local/lib/python3.4/site-packages/klaus/views.py", line 108, in dispatch_request
     return self.get_response()
   File "/home/me/.local/lib/python3.4/site-packages/klaus/views.py", line 111, in get_response
     return render_template(self.template_name, **self.context)
   File "/home/me/.local/lib/python3.4/site-packages/flask/templating.py", line 134, in render_template
     context, ctx.app)
   File "/home/me/.local/lib/python3.4/site-packages/flask/templating.py", line 116, in _render
     rv = template.render(context)
   File "/home/me/.local/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
     return self.environment.handle_exception(exc_info, True)
   File "/home/me/.local/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
     reraise(exc_type, exc_value, tb)
   File "/home/me/.local/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
     raise value.with_traceback(tb)
   File "/home/me/.local/lib/python3.4/site-packages/klaus/templates/blame_blob.html", line 1, in top-level template code
     {% extends 'base.html' %}
   File "/home/me/.local/lib/python3.4/site-packages/klaus/templates/base.html", line 1, in top-level template code
     {% extends 'skeleton.html' %}
   File "/home/me/.local/lib/python3.4/site-packages/klaus/templates/skeleton.html", line 23, in top-level template code
     {% block content %}{% endblock %}
   File "/home/me/.local/lib/python3.4/site-packages/klaus/templates/blame_blob.html", line 30, in block "content"
     <a href="{{ url_for('commit', repo=repo.name, rev=commit.id) }}">{{ commit.id | shorten_sha1 }}</a>
   File "/home/me/.local/lib/python3.4/site-packages/klaus/utils.py", line 172, in shorten_sha1
     if re.match(r'[a-z\d]{20,40}', sha1):
   File "/package/host/localhost/python-3.4.6/lib/python3.4/re.py", line 160, in match
     return _compile(pattern, flags).match(string)
TypeError: can't use a string pattern on a bytes-like object
```

**Comment by slavkoja** [comment]
I encounter this today too, but with Python 3.5. It happens because the ``sha1`` param passed into ``shorten_sha1`` is bytes object and not string expected by ``re.match``. I temporary solved this by adding before mentioned regex in ``site-packages/klaus/utils.py``
```python
def shorten_sha1(sha1):
    if isinstance(sha1, bytes):
        sha1 = sha1.decode()
    if re.match(r'[a-z\d]{20,40}', sha1):
        ...
```
I am not sure about proper solution, because this function is called for more times and with string passed into it too. IMO, it have to be as string in ``context`` already, but i lost in code ;-)

**Comment by FriedrichFroebel** [comment]
Just discovered that this is a known issue (https://github.com/jonashaag/klaus/issues/165), so I am going to close this duplicate.

**Comment by jonashaag** [comment]
It's terrible that this bug went unfixed for almost a year. Thanks for the report.
