### ISSUE TITLE
"Internal Server Error 500" under python3+win10

### ISSUE THREAD

**Issue by bammab** [jonashaag/klaus#202]
Hello,

I used klaus the first time a few hours ago and only the overview works like expected. If I try to open an repo I got an "internal server error", same if I try to "blame" a file (after I fixed the first part). I got it working, but it seems to be a py2/py3 encoding problem...

# Steps to Reproduce the Issue
-Install Python 3.6.2 (32bit) from python website
-cd to targetfolder (e.g. C:\XYZ\UniServerZ\www\)
-Create venv: python -m venv klaus
-cd into and activate: cd klaus; . .\Scripts\activate.ps1
-Install: pip install klaus
-Start with testfolder: (klaus) PS C:\XYZ\UniServerZ\www\klaus> python .\Scripts\klaus --site-name  TestKlaus" "Y:\Repos\repo2.git" Y:\Repos\repo1.git C:\Projekte\repo2
-Open brower (localhost:8080) -> the list of repositories is shown
-Click on any repository -> error

# Expected Behavior
See the information of the repo

# Actual Behavior
Get "internal server error 500" and the console prints the following error / traceback:
``` 
(klaus) PS C:\XYZ\UniServerZ\www\klaus> python .\Scripts\klaus --site-name "TestKlaus" "Y:\
Repos\repo2.git" Y:\Repos\repo1.git C:\Projekte\repo2
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [05/Sep/2017 13:10:49] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2017 13:10:49] "GET /static/pygments.css HTTP/1.1" 304 -
127.0.0.1 - - [05/Sep/2017 13:10:49] "GET /static/klaus.css HTTP/1.1" 304 -
127.0.0.1 - - [05/Sep/2017 13:10:49] "GET /static/klaus.js HTTP/1.1" 304 -
[2017-09-05 13:10:52,965] ERROR in app: Exception on /repo2/ [GET]
Traceback (most recent call last):
  File "C:\XYZ\UniServerZ\www\klaus\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\XYZ\UniServerZ\www\klaus\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\XYZ\UniServerZ\www\klaus\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\XYZ\UniServerZ\www\klaus\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\XYZ\UniServerZ\www\klaus\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\XYZ\UniServerZ\www\klaus\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\XYZ\UniServerZ\www\klaus\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\XYZ\UniServerZ\www\klaus\lib\site-packages\klaus\views.py", line 121, in dispatch_request
    self.make_template_context(repo, rev, path.strip('/'))
  File "C:\XYZ\UniServerZ\www\klaus\lib\site-packages\klaus\views.py", line 259, in make_template_context
    skip=0,
  File "C:\XYZ\UniServerZ\www\klaus\lib\site-packages\klaus\repo.py", line 144, in history
    output = subprocess.check_output(cmd, cwd=os.path.abspath(self.path))
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 966, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
127.0.0.1 - - [05/Sep/2017 13:10:52] "GET /repo2/ HTTP/1.1" 500 - 
```

# Selfmade tests

The error message was a little bit confusing, because not a byates-like object is required, but a str object.

To get rid of the error I need (still now) the following changes in the repo.py:
-line 140: cmd.append(commit.id.decode('utf-8')) #or str(commit.id, encoding='utf-8')
-line 155: cmd = ['git', 'blame', '-ls', '--root', commit.id.decode('utf-8'), '--', path]

Without this changes the output of cmd (from function histroy) looks like:
`output of cmd: ['git', 'log', '--format=%H', '--max-count=11', b'1c9ca6d811ca3de1549bafd179c1f8687810e00e']`

As you can see the commit.id is a bytestring as descript by the docu (https://www.dulwich.io/docs/tutorial/encoding.html). So it seems to be a generic python3 problem?! It would be awesome if someone could check this!

# Debug Information
Python 3.6.2 (32-bit)
OS: Windows 10 (1703) (64-bit)
Klaus: 1.2.1
Admin rights: NO

**Comment by jidn** [comment]
PyPi has a 2017-07-05 update of 1.2.1 but it is using repo.py from June 28 that does not have this fix.  Please update PyPi with the good version.

**Comment by jonashaag** [comment]
Done!
