### ISSUE TITLE
Import error with Markdown README

### ISSUE THREAD

**Issue by FriedrichFroebel** [jonashaag/klaus#235]
Using a `README.md` instead of a `README.rst` file leads to error code 500 "Internal Server Error". Stacktrace from the log file:

```
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.4/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/me/.local/lib/python3.4/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/me/.local/lib/python3.4/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/me/.local/lib/python3.4/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/me/.local/lib/python3.4/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/me/.local/lib/python3.4/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/me/.local/lib/python3.4/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/me/git/klaus/klaus/views.py", line 121, in dispatch_request
    self.make_template_context(repo, rev, path.strip('/'))
  File "/home/me/git/klaus/klaus/views.py", line 285, in make_template_context
    'rendered_code': highlight_or_render(readme_data, readme_filename)
  File "/home/me/git/klaus/klaus/highlighting.py", line 88, in highlight_or_render
    return markup.render(filename, code)
  File "/home/me/git/klaus/klaus/markup.py", line 21, in render
    return get_renderer(filename)(content)
  File "/home/me/git/klaus/klaus/markup.py", line 31, in render_markdown
    return markdown.markdown(content, extensions=['toc', 'extra'])
  File "/home/me/.local/lib/python3.4/site-packages/markdown/core.py", line 390, in markdown
    md = Markdown(**kwargs)
  File "/home/me/.local/lib/python3.4/site-packages/markdown/core.py", line 100, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/home/me/.local/lib/python3.4/site-packages/markdown/core.py", line 126, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/home/me/.local/lib/python3.4/site-packages/markdown/core.py", line 166, in build_extension
    module = importlib.import_module(ext_name)
  File "/package/host/localhost/python-3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'toc'
```

This uses the latest `master`. According to the [docs](https://python-markdown.github.io/extensions/toc/) it seems like the fully qualified extension module path needs to be used as `klaus` does not have a `toc` extension itself which could be imported.

**Comment by FriedrichFroebel** [comment]
For some reason, it magically seems to work now. I have no idea why as I did not change anything since then.
