### ISSUE TITLE
index page is really slow with 1000+ repositories

### ISSUE THREAD

**Issue by jelmer** [jonashaag/klaus#238]
Filing this mostly to track the work I'm doing in this area. With ~2000 repositories loaded, klaus still works well. However, there are two caveats:

* the index page takes a while to load, since it has to open all the repositories
* it runs out of file descriptors, since it (or rather, Dulwich) holds on to file handles to the pack files in all repositories

**Comment by jonashaag** [comment]
@jelmer You have an idea how to fix this in klaus? Have a cache that updates whenever a change has been made to the repository? (Somehow circumventing Dulwich/"properly" loading the repo in Dulwich to save the time it takes to "properly" load the repo)

**Comment by jelmer** [comment]
Yeah, I think we'd want a cache rather than actually reading the repositories every time. Perhaps we could make FancyRepo a wrapper for dulwich.Repo rather than being derived from it?

**Comment by jonashaag** [comment]
OK will look into this soon.

Curious: Do you actually have that kind of use case with 1000+ repos?

**Comment by jonashaag** [comment]
Check this out.

I guess there are a lot more ways to do caching but this one of the simplest things to do.

**Comment by jelmer** [comment]
On Thu, Jul 04, 2019 at 12:59:51AM -0700, Jonas Haag wrote:
> Curious: Do you actually have that kind of use case with 1000+ repos?
Yeah, I'm working on a project to automatically patch Debian Git
repositories, and would like to display the delta somehow. There are
~20k of those. :)

Jelmer

**Comment by jonashaag** [comment]
I'll have to ramp up my benchmark repository then! Tested it with 1k repos, but let me test and optimize with 20k ;)

If you have the time maybe you could help me think about how we can cache ref listing. I was thinking about checking the `stat()` of some Git file or folder for cache invalidation; though I'm not sure there is such a thing as filesystem modification timestamp for "any of the recursive folders or files" that you could use for that. Other caching/cache invalidation ideas?

Of course we can always use simple time-based caching, particularly for information like repository description. But I'd rather use that as a last resort only.

Also inotify etc. but I'm not too keen on integrating that TBH

**Comment by jelmer** [comment]
I've worked around this for now by adding an app that just shows a single repository (a list of 10k repositories is not very usable anyway...) and loads that repository on demand. This works, but is a bit ugly since it has to duplicate some of the logic in klaus (e.g. the route table).

See e.g. https://janitor.debian.net/git/klaus

**Comment by s-ol** [comment]
I'm at ~100 repositories now and I klaus keeps becoming unresponsive due to the file descriptor problem:

```
klaus-1  | Reloading repository list...
klaus-1  | Traceback (most recent call last):
klaus-1  |   File "/usr/lib/python3.10/site-packages/klaus-1.5.2-py3.10.egg/klaus/contrib/wsgi_autoreload_recursive.py", line 74, in app
klaus-1  |   File "/usr/lib/python3.10/site-packages/klaus-1.5.2-py3.10.egg/klaus/contrib/wsgi_autoreload_recursive.py", line 39, in namespaceify
klaus-1  |   File "/usr/lib/python3.10/site-packages/klaus-1.5.2-py3.10.egg/klaus/contrib/wsgi_autoreload_recursive.py", line 23, in find_git_repos_recursive
klaus-1  | OSError: [Errno 24] No file descriptors available: '/srv/git'
klaus-1  | [pid: 1|app: 0|req: 294618/294618] 172.18.0.5 () {52 vars in 1141 bytes} [Tue Apr 21 15:41:24 2026] GET /inkscape/-/blob/e9d20e9e485656ad0124a6525b211abb22ca75b6/man/inkscape.pod.in => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 1)
```

`ulimit -n` is at 1024.

**Comment by jelmer** [comment]
One thing Klaus could do is call .close on repositories after it's done with them. That will close pack files etc that Dulwich keeps open. When objects are requested the pack files are reopened.

This will reduce fd usage at the cost of performance, since index and pack files are repeatedly reopened.
